project:
  type: website
  output-dir: ../docs
  resources:
    - annex/logo.png
    - assets/HCR_Chile_08-06-26.docx
    - data/jmMSE_retuns.slick
    - data/jmMSE_retuns_slick_source.md
  render:
    - index.qmd
    - SCW17-schedule.qmd
    - SCW17-Doc01-Benchmark-to-MSE-Transition.qmd
    - SCW17-TG05-chair-running-sheet.qmd
    - SCW17-TG05-carryover-tracker.qmd
    - SCW17-MSE-Workshop-report.qmd
    - SCW17-MSE-training.qmd
    - SCW17-acronym-glossary.qmd
    - SCW17-Paper-01-ModelDevelopments.qmd
    - SCW17-Paper-02-ReferencePoints.qmd
    - SCW17-Paper-03-Management-Procedures-Inventory.qmd
    - SCW17-Paper-01a-Far-North-Model-Selectivity.qmd
    - SCW17-Paper-04-MSE-Flow.qmd
    - SCW17-Paper-05-Chile-HCR-Proposals.qmd
    - SCW17-Paper-06-Evaluation-of-indices-for-MP-considerations.qmd
    - SCW17-Paper-07-Projection-evaluations.qmd
    - SCW17-Paper-08-MP-tests.qmd

website:
  title: "SPRFMO SCW17"
  site-url: "https://sprfmo.github.io/scw17/"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: https://sprfmo.github.io/scw17/Wageningen-MSE-workshop-schedule.html
        text: SCW17 agenda / schedule
      - href: SCW17-Doc01-Benchmark-to-MSE-Transition.qmd
        text: SCW17/Doc01 Benchmark→MSE
      - href: SCW17-MSE-training.qmd
        text: MSE Training
      - href: SCW17-MSE-Workshop-report.qmd
        text: SCW17 MSE Workshop Report
      - href: SCW17-acronym-glossary.qmd
        text: Glossary
      - href: SCW17-Paper-01-ModelDevelopments.html
        text: SCW17/Paper-01
      - href: SCW17-Paper-01a-Far-North-Model-Selectivity.qmd
        text: SCW17/Paper-01a Far North model selectivity
      - href: SCW17-Paper-02-ReferencePoints.qmd
        text: SCW17/Paper-02
      - href: SCW17-Paper-03-Management-Procedures-Inventory.qmd
        text: SCW17/Paper-03 MP inventory
      - href: SCW17-Paper-04-MSE-Flow.qmd
        text: SCW17/Paper-04 MSE flow
      - href: SCW17-Paper-05-Chile-HCR-Proposals.qmd
        text: SCW17/paper-05 Chile HCR proposals
      - href: SCW17-Paper-06-Evaluation-of-indices-for-MP-considerations.qmd
        text: SCW17/Paper-06 Evaluation of indices for MP considerations
      - href: SCW17-Paper-07-Projection-evaluations.qmd
        text: SCW17/Paper-07 Projection evaluations
      - href: SCW17-Paper-08-MP-tests.qmd
        text: SCW17/Paper-08 MP tests

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    lightbox: true
