project:
  type: website
  output-dir: ../docs
  resources:
    - annex/logo.png
  render:
    - index.qmd
    - SCW17-schedule.qmd
    - SCW17-MSE-training.qmd
    - SCW17-acronym-glossary.qmd
    - SCW17-Paper-01-ModelDevelopments.qmd
    - SCW17-Paper-02-ReferencePoints.qmd
    - SCW17-Paper-03-Management-Procedures-Inventory.qmd
    - SCW17-Paper-01a-Far-North-Model-Selectivity.qmd
    - SCW17-Paper-04-MSE-Flow.qmd

website:
  title: "SPRFMO SCW17"
  site-url: "https://sprfmo.github.io/scw17/"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: https://sprfmo.github.io/scw17/Wageningen-MSE-workshop-schedule.html
        text: SCW17 agenda / schedule
      - href: SCW17-MSE-training.qmd
        text: MSE Training
      - href: SCW17-acronym-glossary.qmd
        text: Glossary
      - href: SCW17-Paper-01-ModelDevelopments.html
        text: SCW17/Paper-01
      - href: SCW17-Paper-01a-Far-North-Model-Selectivity.qmd
        text: SCW17/Paper-01a Far North model selectivity
      - href: SCW17-Paper-02-ReferencePoints.qmd
        text: SCW17/Paper-02
      - href: SCW17-Paper-03-Management-Procedures-Inventory.qmd
        text: SCW17/Paper-03 MP inventory
      - href: SCW17-Paper-04-MSE-Flow.qmd
        text: SCW17/Paper-04 MSE flow

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    lightbox: true
